# webhook-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-acw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-acw
  template:
    metadata:
      labels:
        app: webhook-acw
    spec:
      containers:
      - name: webhook-acw
        image: your-webhook-image:tag
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webhook-acw
  name: webhook-acw
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webhook-acw
  type: ClusterIP

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook-acw
webhooks:
  - name: webhook-acw:8080
    clientConfig:
      service:
        name: webhook-acw
        namespace: default
        path: "/validate-delete-resource"
#      caBundle: YOUR_CA_BUNDLE
    rules:
      - operations: ["DELETE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["serviceinstances.services.cloud.sap.com", "servicebindings.services.cloud.sap.com", "secrets"]
